name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            toolchain: aarch64-apple-darwin,x86_64-apple-darwin
          - host: windows-latest
            toolchain: x86_64-pc-windows-msvc
          - host: ubuntu-latest
            toolchain: x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          target: "${{ matrix.settings.toolchain }}"
      - run: cargo build
