name: CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  web:
    name: Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6.0.9
        with:
          version: 10.17.1
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22.12
          cache: pnpm
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Check format
        run: pnpm check:format
      - name: Lint
        run: pnpm lint
  rust:
    name: Rust (${{ matrix.settings.target }})
    runs-on: "${{ matrix.settings.host }}"
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: aarch64-apple-darwin
            quality: false
          - host: macos-latest
            target: x86_64-apple-darwin
            quality: false
          - host: windows-latest
            target: x86_64-pc-windows-msvc
            quality: false
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            quality: true

    steps:
      - uses: actions/checkout@v7
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt
          target: "${{ matrix.settings.target }}"
      - name: Check format
        if: matrix.settings.quality
        working-directory: crates/cli
        run: cargo fmt --check
      - name: Clippy
        if: matrix.settings.quality
        working-directory: crates/cli
        run: cargo clippy --locked --all-targets -- -D warnings
      - name: Test
        if: matrix.settings.quality
        working-directory: crates/cli
        run: cargo test --locked
      - name: Build
        working-directory: crates/cli
        run: cargo build --locked --release --target "${{ matrix.settings.target }}"
